---
kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: submodules
  image: yaamai/alpine-git:arm64
  commands:
  - git submodule update --init --recursive --remote

# apply patches
- name: patch
  image: yaamai/alpine-git:arm64
  commands:
  - pushd repos/longhorn-engine; patch -p1 ../../longhorn-engine.patch; popd
  - pushd repos/longhorn-manager; patch -p1 ../../longhorn-manager.patch; popd
  - pushd repos/longhorn-instance-manager; patch -p1 ../../longhorn-instance-manager.patch; popd

# build engine
- name: build
  pull: default
  image: library/docker:dind
  commands:
  - pushd repos/longhorn-engine/
  - make
  - popd
