---
kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: submodules
  image: yaamai/alpine-git:arm64
  commands:
  - git submodule update --init --recursive --remote

# apply patches
- name: patch
  image: yaamai/alpine-git:arm64
  commands:
  - cd repos/longhorn-engine; patch -p1 -i ../../longhorn-engine.patch; cd ../..
  - cd repos/longhorn-manager; patch -p1 -i ../../longhorn-manager.patch; cd ../..
  - cd repos/longhorn-instance-manager; patch -p1 -i ../../longhorn-instance-manager.patch; cd ../..

# build engine
- name: build
  pull: default
  image: library/docker:dind
  commands:
  - apk add --update make curl
  - cd repos/longhorn-engine/
  - make
