FROM golang:1.14.1 AS builder
RUN apt-get update && \
    apt-get install -y cmake wget curl git less file \
        libglib2.0-dev libkmod-dev libnl-genl-3-dev linux-libc-dev pkg-config psmisc qemu-utils fuse python-dev \
        devscripts debhelper bash-completion librdmacm-dev libibverbs-dev xsltproc docbook-xsl \
        libconfig-general-perl libaio-dev libc6-dev iptables libltdl7 libdevmapper-dev iproute2 jq

COPY . /src
RUN cd /src/ &&\
    ./scripts/build


# Build liblonghorn
RUN cd /usr/src && \
    git clone https://github.com/rancher/liblonghorn.git && \
    cd liblonghorn && \
    git checkout 6592b9967d1b5acbb51a5596abfe0a0d7bad16dc && \
    make deb && \
    dpkg -i ./pkg/liblonghorn_*.deb

# Build TGT
RUN cd /usr/src && \
    git clone https://github.com/rancher/tgt.git && \
    cd tgt && \
    git checkout e042fdd3616ca90619637b5826695a3de9b5dd8e && \
    ./scripts/build-pkg.sh deb && \
    dpkg -i ./pkg/tgt_*.deb


RUN cp /usr/src/tgt/pkg/tgt_*.deb /src/bin/


FROM ubuntu:18.04
ARG TARGETARCH

RUN apt-get update && apt-get install -y kmod curl nfs-common fuse \
        libibverbs1 librdmacm1 libconfig-general-perl libaio1 sg3-utils \
        iputils-ping telnet iperf qemu-utils wget iproute2

# Install grpc_health_probe
RUN wget -q -O /usr/local/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.3.2/grpc_health_probe-linux-${TARGETARCH} && \
    chmod +x /usr/local/bin/grpc_health_probe

COPY --from=builder /src/bin/longhorn-instance-manager /usr/local/bin/

COPY package/engine-manager /usr/local/bin/

COPY --from=builder /src/bin/tgt_*.deb /opt/

RUN dpkg -i /opt/tgt_*.deb

VOLUME /usr/local/bin

# Add Tini
ENV TINI_VERSION v0.18.0
RUN wget -q -O /tini https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-${TARGETARCH} && \
    chmod +x /tini
ENTRYPOINT ["/tini", "--"]

CMD ["longhorn"]
