name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build ui
      run: ./run.sh ui
    - name: push
      run: sudo ./push.sh
    - name: Build instance-manager
      run: ./run.sh instance-manager
    - name: push
      run: sudo ./push.sh
    - name: Build manager
      run: ./run.sh manager
    - name: push
      run: sudo ./push.sh
    - name: Build engine
      run: ./run.sh engine

    - name: push
      run: sudo ./push.sh
