name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: pwd
    - name: test
      run: ls -alh
    - name: Build the Docker image
      run: env && pwd && ls -alh && ./run ui
